name: Test chill-viking/dotnet-sonar-scanner

on:
  workflow_dispatch:
    inputs:
      pool:
        description: 'Pool to run on'
        required: true
        default: 'windows-latest'
        type: choice
        options:
        - windows-latest
        - ubuntu-latest
      action-version:
        description: 'Branch/tag/version of action to use'
        required: false
        type: string
        default: 'main'

jobs:
  test_and_report_coverage:
    runs-on: ${{ inputs.pool }}
    name: use chill-viking/dotnet-sonar-scanner
    steps:
      - uses: actions/checkout@v3
      - uses: chill-viking/dotnet-sonar-scanner@${{ inputs.action-version }}
        name: use composite action
        with:
          sonar-project-key: 'chill-viking-org_github-actions-tests-dotnet-sonar-scanner'
          sonar-org-key: 'chill-viking-org'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_DOTNET }}
          project-version: '1.0.0-alpha'
          working-directory: './dotnet-sonar-scanner'
